#!/bin/sh
BRANCH=`git branch-name`
[ -z "$BRANCH" ] && exit 1

UPSTREAM=upstream
git remote -v | cut -f1 | grep -q \^"$UPSTREAM"\$ || UPSTREAM=origin

if [ "$BRANCH" = master ]; then
  git fetch "$UPSTREAM"
  git merge --ff-only "$UPSTREAM"/master
else
  git fetch "$UPSTREAM" master
  while ! [ -d .git ]; do
    cd ..
  done
  diff -Naur .git/refs/heads/master .git/refs/remotes/"$UPSTREAM"/master
  cp .git/refs/remotes/"$UPSTREAM"/master .git/refs/heads/master
fi
