#!/bin/sh
set -e

cd ~/utery/manageiq-ui-classic
# git up

# ovirt network hack
git checkout app/controllers/application_controller/network.rb
git up
miq-network

cd ~/utery/manageiq
# git up

# ovirt Gemfile hack
git checkout Gemfile
git up
sed -i -e 's/^  .*ovirt/#&/' Gemfile

bin/update && echo OK || echo FAIL
