#!/bin/sh
swi-pg-run
set -e

cd ~/utery/manageiq-ui-classic
# git up

# ovirt network hack
git checkout app/controllers/application_controller/network.rb
git up

cd ~/utery/manageiq
# git up

# ovirt Gemfile hack
git checkout Gemfile
git up
# macosx sed -i *needs* a param, linux can't use empty one
sed '-i~' -e 's/^  .*ovirt/#&/' Gemfile
rm 'Gemfile~'

bin/update && echo OK || echo FAIL
