#!/bin/sh
cd ~/ctvrtek/manageiq-ui-classic

cat > app/controllers/application_controller/network.rb <<EOF
module ApplicationController::Network
  extend ActiveSupport::Concern

  def network_managers
    ::ManageIQ::Providers::NetworkManager.select(:id, :name, :parent_ems_id)
  end
end
EOF
